### ISSUE TITLE
Single Shapefile Visualization Module for Vesta Cloud

### ISSUE THREAD

**Issue by Luna-Jia** [Luna-Jia/Vesta#2]
**User story**:
As a Vesta Cloud user who needs to visualize spatial data, I want to upload a single shapefile and explore its properties through a color-coded map within the Vesta Cloud platform, so that I can identify patterns in my geographic data for a specific dataset.

* **persona**: GIS analysts, urban planners, and researchers who are Vesta users and need a quick way to visualize a single shapefile directly in the Vesta Cloud environment.

* **feature**: Development of a basic shapefile viewer module within Vesta Cloud that allows users to upload a single shapefile, select properties for visualization, and interact with the resulting color-coded map.

* **business value**: Enhances the Vesta Cloud platform by providing basic spatial data visualization capabilities, allowing users to visualize their data without leaving the Vesta ecosystem.

**Task List**
- [x] Set up the basic HTML structure for the  Vesta Cloud shapefile viewer module.
- [x] Implement file upload functionality for a single set of .shp and .dbf files.
- [x] Create a function to process the uploaded shapefile and convert it to GeoJSON.
- [x] Implement map rendering using Leaflet.js for a single dataset.
- [x] Create a dynamic property selection dropdown for the loaded dataset.
- [x] Implement color scaling based on the selected property.
- [x] Add a legend to explain the color scale.
- [x] Implement feature click functionality to display property popups.
- [x] Ensure the map updates when a new property is selected.

**Acceptance Criteria**
1. Users can upload one set of .shp and .dbf files through the Vesta Cloud interface.
2. The application renders the shapefile as a single color-coded map using Leaflet.js.
3. Users can select different numeric properties from a dropdown to change the map's color coding.
4. The map updates dynamically when a new property is selected.
5. A legend is displayed showing the color scale for the selected property.
6. Clicking on a feature displays a popup with all properties of that feature.

**Acceptance Tests**
1. Verify that users can successfully upload one set of .shp and .dbf files.
2. Check that the map renders correctly with the initial property selection.
3. Confirm that changing the selected property in the dropdown updates the map colors and legend accordingly.
4. Ensure that clicking on map features displays a popup with all relevant property information.
5. Verify that the legend accurately reflects the color scale used in the map.

**Limitations and Future Improvements**
* Currently, only one dataset can be visualized at a time.
* The viewer does not support side-by-side comparison of multiple datasets (e.g., poverty levels and lead contamination in Flint).
* Future iterations could include functionality for uploading and displaying multiple datasets simultaneously for comparative analysis.

https://github.com/Luna-Jia/Vesta/assets/73403516/beb8ec9c-f863-4a01-a868-e28a8b39a2c7

**Comment by Luna-Jia** [comment]
git fetch origin
git checkout 2-single-shapefile-visualization-module-for-vesta-cloud
