### ISSUE TITLE
[TTS-44]Refactor: Split shapefile_viewer.html into separate HTML and JS files

### ISSUE THREAD

**Issue by Luna-Jia** [Luna-Jia/Vesta#7]
**User story**:
---------------------------------------------------------------------------------------
As a developer working on the Vesta project, I want to break down the large shapefile_viewer.html file into separate HTML and JavaScript files so that the code is more maintainable, easier to understand, and simpler to extend in the future.

* **Persona**: Software developers working on the Vesta application who need to manage and expand the codebase efficiently.

* **Feature**: Modularization of the Vesta web application codebase.

* **Business value**: Improves code maintainability, enables easier feature additions, facilitates better team collaboration, and potentially improves application performance through more efficient resource loading.

**Task List**
---------------------------------------------------------------------------------------

- [x] Create a new directory structure for the modularized application.
- [x] Extract all CSS from the HTML file into a separate styles.css file.
- [x] Extract all JavaScript code from shapefile_viewer.html into separate files.
- [x] Create main.js for core functionality and global variables.
- [x] Create a GeoJSONModel class to handle data-related operations.
- [x] Create visualizations.js for all visualization-related functions.
- [x] Create workspace.js for workspace management functions.
- [x] Update shapefile_viewer.html to include the new JavaScript files.
- [x] Remove all inline JavaScript from shapefile_viewer.html.

**Acceptance Criteria**:
---------------------------------------------------------------------------------------

1. The application functionality remains unchanged after the restructuring.
2. The codebase is organized into separate files for HTML, CSS, and JavaScript.
3. JavaScript code is modularized into logical components (e.g., MapController, HistogramController, etc.).
4. A main app.js file coordinates between different modules.
5. CSS is completely separated from HTML and resides in its own file.
6. The index.html file correctly links to all necessary CSS and JavaScript files.
7. The application loads and runs without errors in major browsers (Chrome, Firefox, Safari, Edge).
8. Code duplication is minimized through the use of the modular structure.
9. The new structure allows for easier addition of new features in the future.

**Acceptance Tests**:
---------------------------------------------------------------------------------------

1. Verify that all existing features (map rendering, histogram creation, table display, workspace management, data import) work as before.
2. Check that the browser console shows no errors related to missing files or undefined functions.
3.Confirm that modifying a single JavaScript file (e.g., visualizations.js) doesn't affect the functionality in other files.
4. Test adding a new feature to ensure the modular structure facilitates easy expansion.
5. Verify that the application's initial load time hasn't significantly increased due to the restructuring.
6. Check that all styles are applied correctly from the external CSS file.

**Comment by Luna-Jia** [comment]
git fetch origin
git checkout 7-mvcRefactor
